In [1]:
import pandas as pd
import time
from datetime import datetime

import warnings
warnings.filterwarnings('ignore')

In [2]:
option_data = pd.read_csv('C:\\Users\\gaura\\Main_Project_EPAT\\Final\\Options_data_2023_BN.csv')

In [3]:
option_data['Date'] = pd.to_datetime(option_data['Date'])
option_data.head()

,Unnamed: 0,Date,Ticker,Time,Open,High,Low,Close,Call/Put
0,0,2023-01-02,BANKNIFTY37000PE,9:15:59,3.40,3.40,2.85,3.00,PE
1,1,2023-01-02,BANKNIFTY43800CE,9:15:59,79.85,104.25,73.90,91.20,CE
2,2,2023-01-02,BANKNIFTY43900PE,9:15:59,867.95,883.15,826.75,826.75,PE
3,3,2023-01-02,BANKNIFTY44000PE,9:15:59,957.25,981.05,911.00,914.70,PE
4,4,2023-01-02,BANKNIFTY44200CE,9:15:59,37.90,42.95,27.35,37.10,CE

In [4]:
option_data_new = option_data.drop(columns=['Unnamed: 0'],inplace=True)

In [5]:
option_data.head()

,Date,Ticker,Time,Open,High,Low,Close,Call/Put
0,2023-01-02,BANKNIFTY37000PE,9:15:59,3.40,3.40,2.85,3.00,PE
1,2023-01-02,BANKNIFTY43800CE,9:15:59,79.85,104.25,73.90,91.20,CE
2,2023-01-02,BANKNIFTY43900PE,9:15:59,867.95,883.15,826.75,826.75,PE
3,2023-01-02,BANKNIFTY44000PE,9:15:59,957.25,981.05,911.00,914.70,PE
4,2023-01-02,BANKNIFTY44200CE,9:15:59,37.90,42.95,27.35,37.10,CE

In [6]:
option_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 8 columns):
 #   Column    Non-Null Count    Dtype
---  ------    --------------    -----
 0   Date      1048575 non-null  datetime64[us]
 1   Ticker    1048575 non-null  str
 2   Time      1048575 non-null  str
 3   Open      1048575 non-null  float64
 4   High      1048575 non-null  float64
 5   Low       1048575 non-null  float64
 6   Close     1048575 non-null  float64
 7   Call/Put  1048575 non-null  str
dtypes: datetime64[us](1), float64(4), str(3)
memory usage: 89.9 MB

In [7]:
option_data['strike_price']=  option_data['Ticker'].apply(lambda x: ''.join(filter(str.isdigit, x)))

print(option_data)

              Date            Ticker     Time     Open     High      Low  \
0       2023-01-02  BANKNIFTY37000PE  9:15:59     3.40     3.40     2.85
1       2023-01-02  BANKNIFTY43800CE  9:15:59    79.85   104.25    73.90
2       2023-01-02  BANKNIFTY43900PE  9:15:59   867.95   883.15   826.75
3       2023-01-02  BANKNIFTY44000PE  9:15:59   957.25   981.05   911.00
4       2023-01-02  BANKNIFTY44200CE  9:15:59    37.90    42.95    27.35
...            ...               ...      ...      ...      ...      ...
1048570 2023-02-08  BANKNIFTY43200CE  9:34:59     5.30     5.30     5.20
1048571 2023-02-08  BANKNIFTY43100CE  9:34:59     5.95     6.00     5.90
1048572 2023-02-08  BANKNIFTY43000PE  9:34:59  1368.70  1368.70  1354.30
1048573 2023-02-08  BANKNIFTY35500PE  9:34:59     2.15     2.25     2.15
1048574 2023-02-08  BANKNIFTY36000PE  9:34:59     2.30     2.30     2.25

           Close Call/Put strike_price
0           3.00       PE        37000
1          91.20       CE        43800
2         826.75       PE        43900
3         914.70       PE        44000
4          37.10       CE        44200
...          ...      ...          ...
1048570     5.30       CE        43200
1048571     5.90       CE        43100
1048572  1354.30       PE        43000
1048573     2.25       PE        35500
1048574     2.30       PE        36000

[1048575 rows x 9 columns]

In [8]:
# Create Expiry column
option_data['Expiry'] = option_data['Date'] + pd.offsets.Week(weekday=4)

# Days difference
option_data['Days_to_Expiry'] = (
    option_data['Expiry'] - option_data['Date']
).dt.days

print(option_data.tail())

        Date            Ticker     Time    Open    High     Low   Close  \
0 2023-01-02  BANKNIFTY37000PE  9:15:59    3.40    3.40    2.85    3.00
1 2023-01-02  BANKNIFTY43800CE  9:15:59   79.85  104.25   73.90   91.20
2 2023-01-02  BANKNIFTY43900PE  9:15:59  867.95  883.15  826.75  826.75
3 2023-01-02  BANKNIFTY44000PE  9:15:59  957.25  981.05  911.00  914.70
4 2023-01-02  BANKNIFTY44200CE  9:15:59   37.90   42.95   27.35   37.10

  Call/Put strike_price     Expiry  Days_to_Expiry
0       PE        37000 2023-01-06               4
1       CE        43800 2023-01-06               4
2       PE        43900 2023-01-06               4
3       PE        44000 2023-01-06               4
4       CE        44200 2023-01-06               4

In [9]:
type(option_data)

pandas.DataFrame

In [10]:
print(option_data.tail())

              Date            Ticker     Time     Open     High      Low  \
1048570 2023-02-08  BANKNIFTY43200CE  9:34:59     5.30     5.30     5.20
1048571 2023-02-08  BANKNIFTY43100CE  9:34:59     5.95     6.00     5.90
1048572 2023-02-08  BANKNIFTY43000PE  9:34:59  1368.70  1368.70  1354.30
1048573 2023-02-08  BANKNIFTY35500PE  9:34:59     2.15     2.25     2.15
1048574 2023-02-08  BANKNIFTY36000PE  9:34:59     2.30     2.30     2.25

           Close Call/Put strike_price     Expiry  Days_to_Expiry
1048570     5.30       CE        43200 2023-02-10               2
1048571     5.90       CE        43100 2023-02-10               2
1048572  1354.30       PE        43000 2023-02-10               2
1048573     2.25       PE        35500 2023-02-10               2
1048574     2.30       PE        36000 2023-02-10               2

In [15]:
daily_option = option_data.groupby(['Date','Ticker']).agg({
        'Open': 'first',
        'High': 'max',
        'Low': 'min',
        'Close': 'last',
        'Call/Put': 'first',
        'strike_price' : 'first',
        'Expiry' : 'first',
        'Days_to_Expiry' : 'first' 
})

In [16]:
print(daily_option)

                                Open     High      Low    Close Call/Put  \
Date       Ticker
2023-01-02 BANKNIFTY36500PE     2.90     3.10     2.25     2.50       PE
           BANKNIFTY37000PE     3.40     3.40     2.35     2.45       PE
           BANKNIFTY37500PE     3.50     3.50     2.60     3.05       PE
           BANKNIFTY38000CE  5224.15  5230.00  5224.15  5230.00       CE
           BANKNIFTY38000PE     2.10     3.70     2.10     3.05       PE
...                              ...      ...      ...      ...      ...
2023-02-08 BANKNIFTY46000CE     1.65     2.30     1.65     1.85       CE
           BANKNIFTY46500CE     1.90     2.25     1.80     1.90       CE
           BANKNIFTY47000CE     1.75     2.25     1.70     1.80       CE
           BANKNIFTY47500CE     1.80     2.25     1.70     1.80       CE
           BANKNIFTY48000CE     1.50     2.20     1.50     1.75       CE

                            strike_price     Expiry  Days_to_Expiry
Date       Ticker
2023-01-02 BANKNIFTY36500PE        36500 2023-01-06               4
           BANKNIFTY37000PE        37000 2023-01-06               4
           BANKNIFTY37500PE        37500 2023-01-06               4
           BANKNIFTY38000CE        38000 2023-01-06               4
           BANKNIFTY38000PE        38000 2023-01-06               4
...                                  ...        ...             ...
2023-02-08 BANKNIFTY46000CE        46000 2023-02-10               2
           BANKNIFTY46500CE        46500 2023-02-10               2
           BANKNIFTY47000CE        47000 2023-02-10               2
           BANKNIFTY47500CE        47500 2023-02-10               2
           BANKNIFTY48000CE        48000 2023-02-10               2

[3851 rows x 8 columns]

In [11]:
bank_nifty = pd.read_csv('C:\\Users\\gaura\\Main_Project_EPAT\\Final\\BAnk_nifty.csv')

print(bank_nifty.head())

                        Date          Open          High           Low  \
0  2023-01-02 00:00:00+05:30  43038.250000  43382.750000  42961.750000
1  2023-01-03 00:00:00+05:30  43151.449219  43482.800781  43148.449219
2  2023-01-04 00:00:00+05:30  43417.500000  43578.398438  42858.648438
3  2023-01-05 00:00:00+05:30  43073.050781  43137.550781  42298.601562
4  2023-01-06 00:00:00+05:30  42649.699219  42685.898438  41877.000000

          Close      Volume  Dividends  Stock Splits
0  43203.101562  1798102100        0.0           0.0
1  43425.250000      197000        0.0           0.0
2  42958.800781      216800        0.0           0.0
3  42608.699219      189100        0.0           0.0
4  42188.800781      195100        0.0           0.0

In [19]:
bank_nifty.rename(columns= {'Open' : 'BN_open',
                   'High' : 'BN_high',
                   'Low' : 'BN_low',
                   'Close' : 'BN_close'})

,Date,BN_open,BN_high,BN_low,BN_close,Volume,Dividends,Stock Splits
0,2023-01-02 00:00:00+05:30,43038.250000,43382.750000,42961.750000,43203.101562,1798102100,0.0,0.0
1,2023-01-03 00:00:00+05:30,43151.449219,43482.800781,43148.449219,43425.250000,197000,0.0,0.0
2,2023-01-04 00:00:00+05:30,43417.500000,43578.398438,42858.648438,42958.800781,216800,0.0,0.0
3,2023-01-05 00:00:00+05:30,43073.050781,43137.550781,42298.601562,42608.699219,189100,0.0,0.0
4,2023-01-06 00:00:00+05:30,42649.699219,42685.898438,41877.000000,42188.800781,195100,0.0,0.0
5,2023-01-09 00:00:00+05:30,42404.851562,42716.800781,42186.550781,42582.750000,161800,0.0,0.0
6,2023-01-10 00:00:00+05:30,42642.000000,42674.250000,41835.750000,42014.750000,179300,0.0,0.0
7,2023-01-11 00:00:00+05:30,42071.851562,42318.000000,41729.000000,42232.699219,169800,0.0,0.0
8,2023-01-12 00:00:00+05:30,42238.500000,42343.500000,41742.949219,42082.250000,154100,0.0,0.0
9,2023-01-13 00:00:00+05:30,42171.250000,42453.949219,41885.601562,42371.250000,205500,0.0,0.0
10,2023-01-16 00:00:00+05:30,42622.500000,42715.648438,42066.550781,42167.550781,312300,0.0,0.0
11,2023-01-17 00:00:00+05:30,42241.199219,42383.800781,41861.101562,42235.050781,256300,0.0,0.0
12,2023-01-18 00:00:00+05:30,42271.800781,42555.898438,42119.648438,42458.000000,170500,0.0,0.0
13,2023-01-19 00:00:00+05:30,42416.300781,42506.250000,42234.898438,42328.851562,143400,0.0,0.0
14,2023-01-20 00:00:00+05:30,42516.050781,42709.199219,42366.148438,42506.800781,159100,0.0,0.0
15,2023-01-23 00:00:00+05:30,42891.449219,43005.851562,42727.699219,42821.250000,203600,0.0,0.0
16,2023-01-24 00:00:00+05:30,42994.449219,43078.898438,42615.648438,42733.449219,159500,0.0,0.0
17,2023-01-25 00:00:00+05:30,42703.601562,42733.050781,41540.300781,41647.648438,244700,0.0,0.0
18,2023-01-27 00:00:00+05:30,41382.351562,41417.898438,40148.800781,40345.300781,350800,0.0,0.0
19,2023-01-30 00:00:00+05:30,39856.148438,40789.550781,39419.800781,40387.449219,369900,0.0,0.0
20,2023-01-31 00:00:00+05:30,40563.851562,40811.648438,40167.699219,40655.050781,289900,0.0,0.0
21,2023-02-01 00:00:00+05:30,41115.000000,42015.648438,39490.500000,40513.000000,400100,0.0,0.0
22,2023-02-02 00:00:00+05:30,39943.351562,40757.601562,39761.449219,40669.300781,348500,0.0,0.0
23,2023-02-03 00:00:00+05:30,41019.351562,41539.949219,40609.750000,41499.699219,308800,0.0,0.0
24,2023-02-06 00:00:00+05:30,41530.148438,41724.500000,41261.199219,41374.648438,197800,0.0,0.0
25,2023-02-07 00:00:00+05:30,41513.101562,41630.750000,41095.101562,41490.949219,171900,0.0,0.0

In [22]:
bank_nifty['Date'] = pd.to_datetime(
    bank_nifty['Date']
).dt.tz_localize(None)

In [26]:
main_dataset = pd.merge(
    daily_option,
    bank_nifty[['Date', 'Open']],
    on='Date',
    how='left'
)

print(main_dataset.head())

        Date   Open_x    High      Low    Close Call/Put strike_price  \
0 2023-01-02     2.90     3.1     2.25     2.50       PE        36500
1 2023-01-02     3.40     3.4     2.35     2.45       PE        37000
2 2023-01-02     3.50     3.5     2.60     3.05       PE        37500
3 2023-01-02  5224.15  5230.0  5224.15  5230.00       CE        38000
4 2023-01-02     2.10     3.7     2.10     3.05       PE        38000

      Expiry  Days_to_Expiry    Open_y
0 2023-01-06               4  43038.25
1 2023-01-06               4  43038.25
2 2023-01-06               4  43038.25
3 2023-01-06               4  43038.25
4 2023-01-06               4  43038.25

In [27]:
type(main_dataset)

pandas.DataFrame

In [29]:
r = 0.065

In [40]:
!pip install mibian

from mibian import BS

Requirement already satisfied: mibian in c:\users\gaura\anaconda3\lib\site-packages (0.1.3)

In [ ]:
def calculate_iv(row):

    S = row['Open_y']              # underlying price
    K = row['strike_price']        # strike
    r = 0.065                      # interest rate %
    q = 0                          # dividend yield
    dte = row['Days_to_Expiry']    # days to expiry
    option_price = row['Open_x']
    try:
        if row['Call/Put'] == 'CE':
            me = BS.Me(
                [S, K, r, q, dte],
                callPrice=option_price)
        else:
            me = BS.Me(
                [S, K, r, q, dte],
                putPrice=option_price)
        return me.impliedVolatility
    except:
        return None
# apply row-wise
main_dataset['IV'] = main_dataset.apply(calculate_iv, axis=1)

print(main_dataset)

           Date   Open_x     High      Low    Close Call/Put strike_price  \
0    2023-01-02     2.90     3.10     2.25     2.50       PE        36500
1    2023-01-02     3.40     3.40     2.35     2.45       PE        37000
2    2023-01-02     3.50     3.50     2.60     3.05       PE        37500
3    2023-01-02  5224.15  5230.00  5224.15  5230.00       CE        38000
4    2023-01-02     2.10     3.70     2.10     3.05       PE        38000
...         ...      ...      ...      ...      ...      ...          ...
3846 2023-02-08     1.65     2.30     1.65     1.85       CE        46000
3847 2023-02-08     1.90     2.25     1.80     1.90       CE        46500
3848 2023-02-08     1.75     2.25     1.70     1.80       CE        47000
3849 2023-02-08     1.80     2.25     1.70     1.80       CE        47500
3850 2023-02-08     1.50     2.20     1.50     1.75       CE        48000

         Expiry  Days_to_Expiry    Open_y    IV
0    2023-01-06               4  43038.25  None
1    2023-01-06               4  43038.25  None
2    2023-01-06               4  43038.25  None
3    2023-01-06               4  43038.25  None
4    2023-01-06               4  43038.25  None
...         ...             ...       ...   ...
3846 2023-02-10               2       NaN  None
3847 2023-02-10               2       NaN  None
3848 2023-02-10               2       NaN  None
3849 2023-02-10               2       NaN  None
3850 2023-02-10               2       NaN  None

[3851 rows x 11 columns]